"""empty message

Revision ID: ffb9854ba072
Revises: 
Create Date: 2023-08-19 09:36:07.192345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffb9854ba072'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_fullname', sa.String(length=100), nullable=False),
    sa.Column('user_email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('donation',
    sa.Column('don_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('don_amt', sa.Float(), nullable=False),
    sa.Column('don_userid', sa.Integer(), nullable=True),
    sa.Column('don_fullname', sa.String(length=100), nullable=True),
    sa.Column('don_email', sa.String(length=100), nullable=True),
    sa.Column('don_refno', sa.String(length=20), nullable=False),
    sa.Column('don_paygate_response', sa.Text(), nullable=True),
    sa.Column('don_date', sa.DateTime(), nullable=True),
    sa.Column('don_status', sa.Enum('pending', 'failed', 'paid'), server_default='pending', nullable=False),
    sa.ForeignKeyConstraint(['don_userid'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('don_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donation')
    op.drop_table('user')
    # ### end Alembic commands ###
